server:
  port: 9999

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8999/realms/Fitness-Oauth/protocol/openid-connect/certs
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ACTIVITY-SERVICE
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activity/**
        - id: AI-SERVICE
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendation/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/fitness-app/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip: true
